// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/store": {
    params: {};
  };
  "/products": {
    params: {};
  };
  "/products/:id": {
    params: {
      "id": string;
    };
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/profile": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/store" | "/products" | "/products/:id" | "/login" | "/register" | "/profile";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/store.tsx": {
    id: "routes/store";
    page: "/store";
  };
  "routes/products.tsx": {
    id: "routes/products";
    page: "/products";
  };
  "routes/products/$id.tsx": {
    id: "routes/products/$id";
    page: "/products/:id";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/profile.tsx": {
    id: "routes/profile";
    page: "/profile";
  };
};